set autocommit off;
set define off;
DROP TABLE PURGE;
CREATE TABLE (
	year	integer,
	state	varchar2(7),
	county 	varchar2(69),
	LEA_ID	integer,
	LEA_CTDS	integer,
	LEA_name	varchar2(169),
	school_id	integer,
	school_CTDS	integer,
	school_name	varchar2(169),
	is_charter	char(1),
	math_mean 	integer,
	math_pctFFB	integer,
	math_pctA	integer,
	math_pctM	integer,
	math_pctE	integer,
	math_pctP	integer,
	read_mean	integer,
	read_pctFFB	integer,
	read_pctA	integer,
	read_pctM	integer,
	read_pctE	integer,
	read_pctP	integer,
	writ_mean	integer,
	writ_pctFFB	integer,
	writ_pctA	integer,
	writ_pctM	integer,
	writ_pctE	integer,
	writ_pctP	integer,
	sci_mean	integer,
	sci_pctFFB	integer,
	sci_pctA	integer,
	sci_pctM	integer,
	sci_pctE	integer,
	sci_pctP	integer);
